"""change song_image to song_profile

Revision ID: a0b7aef0f033
Revises: ce98d7f73759
Create Date: 2024-06-14 18:14:59.792911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b7aef0f033'
down_revision = 'ce98d7f73759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_profile', sa.String(length=255), nullable=True))
        batch_op.drop_column('song_image')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_creater', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_creater')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_image', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('song_profile')

    # ### end Alembic commands ###
