"""empty message

Revision ID: c1fa4e358113
Revises: 9a563604c986
Create Date: 2024-06-14 19:30:56.535029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fa4e358113'
down_revision = '9a563604c986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_profile', sa.String(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.drop_column('mimetype_profile')

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('song_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('song_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype_profile', sa.TEXT(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('playlist_profile')

    # ### end Alembic commands ###
