"""added song file to Song model

Revision ID: ce98d7f73759
Revises: ce7e1b0b9c09
Create Date: 2024-06-14 17:11:10.856940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce98d7f73759'
down_revision = 'ce7e1b0b9c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('song_image')

    # ### end Alembic commands ###
